# Generated by Django 4.1.7 on 2023-05-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerImage',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
