# Generated by Django 4.1.7 on 2023-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
